### PR TITLE
feat: cache fitness values for deme

### PR DESCRIPTION
**Pull request by WojtAcht**
At the beginning of each GA metaepoch fitness function is evaluated for the whole population. It's really inefficient.

### CODE REVIEW

**Comment by WojtAcht** [comment]
It would be better to create PR with new parameter (`fitnessSuggestions`) to the `GA` repo.

**Comment by WojtAcht** [comment]
TODO: check package memoise

**Comment by WojtAcht** [comment]
Without cache:
|n|function_name         |budget|mean_time |min          |q_25        |q_50        |mean        |q_75        |max         |
|----|----------------------|------|----------|-------------|------------|------------|------------|------------|------------|
| 1  |10-d Ackley Function  | 1000 |0.05020698| 4.214737e+00|   5.7953285|   6.6442657|   6.5828794|   7.4406984|   9.4570188|
| 2  |10-d Ackley Function  | 5000 |0.24170172| 1.228139e+00|   2.7047649|   2.9009055|   2.8563282|   3.0416522|   4.0404629|
| 3  |10-d Ackley Function  |10000 |0.47956517| 5.307234e-01|   1.0355577|   1.5234055|   1.4730290|   1.8235011|   2.4029343|
| 4  |10-d Ackley Function  |15000 |0.70689552| 2.446765e-01|   0.4681060|   0.6260744|   0.7014293|   0.8827091|   1.4260324|
| 5  |Egg Holder Function   | 1000 |0.03097320|-9.562503e+02|-934.3615944|-894.5368151|-878.9563391|-888.8261158|-627.6951006|
| 6  |Egg Holder Function   | 5000 |0.14450075|-9.591194e+02|-955.5037345|-935.3054210|-918.4238002|-894.5767374|-718.1332741|
| 7  |Egg Holder Function   |10000 |0.27830172|-9.591194e+02|-956.8548702|-935.3379028|-926.4098294|-894.5788922|-718.1440363|
| 8  |Egg Holder Function   |15000 |0.40399574|-9.591194e+02|-956.9123094|-956.8173144|-942.3009340|-935.3338433|-888.9449814|
| 9  |10-d Griewank Function| 1000 |0.04574443| 5.251913e-01|   0.8200185|   0.9397980|   0.9041791|   1.0035805|   1.1585434|
|10  |10-d Griewank Function| 5000 |0.21890152| 2.293242e-01|   0.4126000|   0.5251913|   0.5118249|   0.5737118|   0.7473560|
|11  |10-d Griewank Function|10000 |0.45601873| 1.318141e-01|   0.2985411|   0.3751765|   0.3734068|   0.4298021|   0.7319169|
|12  |10-d Griewank Function|15000 |0.63387312| 1.318141e-01|   0.2130078|   0.2913917|   0.2975327|   0.3534536|   0.7319169|
|13  |5-d Rastrigin Function| 1000 |0.03617105| 1.138986e+00|   3.7188844|   4.6983684|   5.4303996|   7.0497386|  12.4638600|
|14  |5-d Rastrigin Function| 5000 |0.21182231| 1.370180e-01|   1.2540637|   2.1342500|   2.1806209|   2.6130012|   4.4891049|
|15  |5-d Rastrigin Function|10000 |0.41739199| 4.475589e-03|   0.9008014|   1.1192022|   1.4188780|   2.0277778|   3.0250531|
|16  |5-d Rastrigin Function|15000 |0.61646934| 4.154417e-03|   0.2694699|   1.0176910|   1.0669877|   1.6334938|   3.0084054|

**Comment by WojtAcht** [comment]
With cache:
|n|function_name         |budget|mean_time|min          |q_25         |q_50        |mean        |q_75        |max         |
|----|----------------------|------|---------|-------------|-------------|------------|------------|------------|------------|
| 1  |10-d Ackley Function  | 1000 |0.1793672| 4.214737e+00|   5.46102283|   6.4465965|   6.2632021|   6.8116650|   8.5313025|
| 2  |10-d Ackley Function  | 5000 |0.9198516| 8.149785e-01|   2.08366536|   2.4781532|   2.3428355|   2.6463050|   3.1768228|
| 3  |10-d Ackley Function  |10000 |1.8434934| 3.247627e-01|   0.59848097|   0.9327976|   0.9112316|   1.1200733|   1.7882145|
| 4  |10-d Ackley Function  |15000 |2.7540679| 8.372291e-02|   0.24928502|   0.3742987|   0.4175998|   0.5516294|   0.8475697|
| 5  |Egg Holder Function   | 1000 |0.1589863|-9.562503e+02|-934.89661045|-894.5368151|-880.2969472|-888.8356753|-628.9960302|
| 6  |Egg Holder Function   | 5000 |0.8341562|-9.591194e+02|-956.20436642|-935.3344473|-923.0702993|-894.5784406|-718.1332741|
| 7  |Egg Holder Function   |10000 |1.6183143|-9.591194e+02|-956.91230944|-955.9461132|-937.2938408|-919.5004718|-888.9449814|
| 8  |Egg Holder Function   |15000 |2.3163974|-9.591194e+02|-956.91230944|-956.8653784|-945.3505089|-935.3361876|-888.9491118|
| 9  |10-d Griewank Function| 1000 |0.1793149| 5.251913e-01|   0.80036854|   0.8896278|   0.8756187|   0.9950822|   1.1585434|
|10  |10-d Griewank Function| 5000 |0.9363306| 2.157867e-01|   0.36886829|   0.4314033|   0.4399134|   0.5081225|   0.7473560|
|11  |10-d Griewank Function|10000 |1.8448253| 1.318141e-01|   0.23983575|   0.3152537|   0.3295634|   0.3813923|   0.7319169|
|12  |10-d Griewank Function|15000 |2.6561993| 1.318141e-01|   0.21116683|   0.2654181|   0.2767086|   0.3370350|   0.5941254|
|13  |5-d Rastrigin Function| 1000 |0.1834235| 1.138986e+00|   3.24821383|   3.8640010|   4.3054106|   6.2739901|   8.4086913|
|14  |5-d Rastrigin Function| 5000 |0.8982519| 9.536266e-02|   1.13635095|   2.0559277|   1.9753645|   2.3190734|   4.1381001|
|15  |5-d Rastrigin Function|10000 |1.8217036| 4.154417e-03|   0.29445008|   1.0197250|   1.1690472|   1.9973731|   3.0084054|
|16  |5-d Rastrigin Function|15000 |2.6964780| 1.511917e-03|   0.09385877|   0.4568535|   0.6316880|   1.0638119|   2.0059307|

**Comment by WojtAcht** [comment]
```
> results_without_cache$mean
 [1]    6.5828794    2.8563282    1.4730290    0.7014293 -878.9563391 -918.4238002 -926.4098294 -942.3009340
 [9]    0.9041791    0.5118249    0.3734068    0.2975327    5.4303996    2.1806209    1.4188780    1.0669877
> results_with_cache$mean
 [1]    6.2632021    2.3428355    0.9112316    0.4175998 -880.2969472 -923.0702993 -937.2938408 -945.3505089
 [9]    0.8756187    0.4399134    0.3295634    0.2767086    4.3054106    1.9753645    1.1690472    0.6316880
> results_with_cache$mean - results_without_cache$mean
 [1]  -0.31967723  -0.51349269  -0.56179736  -0.28382944  -1.34060815  -4.64649911 -10.88401139  -3.04957494
 [9]  -0.02856038  -0.07191150  -0.04384341  -0.02082414  -1.12498903  -0.20525645  -0.24983076  -0.43529970
```

Clearly, the use of cache enhanced the average fitness value in every instance.

**Comment by WojtAcht** [comment]
It also increased the average time ~ 4x.
```
> results_with_cache$mean_time / results_without_cache$mean_time
 [1] 3.572555 3.805731 3.844094 3.896004 5.133030 5.772678 5.814963 5.733717 3.919930 4.277406 4.045503 4.190427
[13] 5.071004 4.240592 4.364491 4.374067
```

**Comment by WojtAcht** [comment]
I run it once again for custom cache (cache only for fitness_values from last epoch):
```
> custom_cache_results$mean - without_cache_results$mean
 [1]   0.33592959   0.19637211   0.45168255   0.89969000 -15.64625483  -7.33841406  -9.21562939  -0.21327108
 [9]   0.04973905   0.09556659   0.07633412   0.07688382  -1.23844772  -0.29525138   0.09736759   0.14521796
> custom_cache_results$mean_time - without_cache_results$mean_time
 [1] 0.06299868 0.34252121 0.67956243 0.99045144 0.05927082 0.28387454 0.59214837 0.90846423 0.05664635 0.34358271
[11] 0.64051270 0.95137358 0.06581655 0.28751428 0.61055393 0.92879450
```

I don't understand why sometimes it's worse than hms without cache.

**Review by KartonM — APPROVED** [review]

**Pull request merged**
